language: java
sudo: false
dist: trusty

# build tickle

notifications:
    email: false

jdk:
  - oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

install:
- find . -name "*.sh" -exec chmod u+x {} \;
# this is using Java 9 but that's OK for our purposes here
- echo "------------------ eg_01_java_8"
- cd eg_01_java_8
- ./build_and_run.sh
- echo "------------------ eg_02_java_9_simple"
- cd ../eg_02_java_9_simple
- ./build_and_run.sh
- echo "------------------ eg_03_1_open_fail"
- cd ../eg_03_1_open_fail
- ./build_and_run.sh
- echo "------------------ eg_03_2_open_module"
- cd ../eg_03_2_open_module
- ./build_and_run.sh
- echo "------------------ eg_03_3_java_9_command_line"
- cd ../eg_03_3_java_9_command_line
- ./build_and_run.sh
- echo "------------------ eg_04_java_9_automatic_module"
- cd ../eg_04_java_9_automatic_module
- ./prepare_build_run.sh
- echo "------------------ eg_05_java_9_jlink"
- cd ../eg_05_java_9_jlink
- ./build_link_run.sh

- cd ..
