language: java
sudo: false
dist: trusty

# build tickle

notifications:
    email: false

jdk:
  - oraclejdk9

addons:
  apt:
    packages:
      - oracle-java9-installer

install:
- find . -name "*.sh" -exec chmod u+x {} \;
# this is using Java 9 but that's OK for our purposes here
- echo "------------------ eg_01_java_8"
- cd eg_01_java_8
- ./build_and_run.sh
- echo "------------------ eg_02_java_9_simple"
- cd ../eg_02_java_9_simple"
- ./build_and_run.sh

- cd ..
